global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'crypto-bot'
    static_configs:
      - targets: ['crypto-bot:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
